const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
function setup(path='/owner/repo/blob/feature/nested/src/app.js',text='first\nsecond\nthird'){
 const d=new JSDOM('<div id="repos-header-breadcrumb--wide"><a>repo</a><a>src</a></div><h1 id="file-name-id-wide">app.js</h1><textarea id="read-only-cursor-text-area"></textarea><div data-line-number="2">2</div>',{url:'https://github.com'+path,runScripts:'outside-only'});d.window.GHE={};d.window.TextEncoder=TextEncoder;d.window.document.querySelector('textarea').value=text;d.window.eval(fs.readFileSync('src/content/code-tools.js','utf8'));return d;
}
test('code adapter reads visible source and breadcrumb path without guessing slash-containing refs',()=>{const d=setup();d.window.location.hash='#L2-L3';const c=d.window.GHE.collectCode(d.window.document,{});assert.equal(c.path,'src/app.js');assert.equal(c.language,'javascript');assert.equal(c.lineCount,3);assert.equal(c.text,'first\nsecond\nthird');assert.deepEqual(JSON.parse(JSON.stringify(c.selection)),{start:2,end:3});d.window.close();});
test('code adapter bounds large source and never claims a partial file complete',()=>{const d=setup(undefined,'a'.repeat(310000));const c=d.window.GHE.collectCode(d.window.document,{});assert.equal(c.text.length,300000);assert.equal(c.truncated,true);d.window.close();});
test('code tools ignore non-file routes and reject out-of-range jumps',()=>{const d=setup('/owner/repo/issues/1');assert.equal(d.window.GHE.collectCode(d.window.document,{}),null);assert.equal(d.window.GHE.codeAction(d.window.document,{type:'code-jump',line:2}),false);d.window.history.replaceState({},'','/owner/repo/blob/main/a.js');assert.equal(d.window.GHE.codeAction(d.window.document,{type:'code-jump',line:-1}),false);let jumped=false;d.window.document.querySelector('[data-line-number]').scrollIntoView=()=>jumped=true;assert.equal(d.window.GHE.codeAction(d.window.document,{type:'code-jump',line:2}),true);assert.equal(jumped,true);assert.equal(d.window.location.hash,'#L2');d.window.close();});

test('unavailable URL and textarea selections retain their requested lines instead of substituting a loaded range',()=>{
 const full='123456789\n'.repeat(90002),d=setup(undefined,full);d.window.location.hash='#L90001-L90002';let c=d.window.GHE.collectCode(d.window.document);assert.deepEqual(JSON.parse(JSON.stringify(c.selection)),{start:90001,end:90002});assert.match(c.selectionError,/loaded/i);assert.equal(c.lineCount,30000);
 d.window.location.hash='';const area=d.window.document.querySelector('textarea');area.selectionStart=900000;area.selectionEnd=900019;c=d.window.GHE.collectCode(d.window.document);assert.deepEqual(JSON.parse(JSON.stringify(c.selection)),{start:90001,end:90002});assert.match(c.selectionError,/30000|30,000/);d.window.close();
});
test('a selected partial final line is unavailable while fully represented lines remain usable',()=>{
 const d=setup(undefined,'first\nsecond\n'+'a'.repeat(300000));d.window.location.hash='#L3';let c=d.window.GHE.collectCode(d.window.document);assert.equal(c.selection.start,3);assert.equal(c.lineCount,2);assert.match(c.selectionError,/fully|available/i);d.window.location.hash='#L2';c=d.window.GHE.collectCode(d.window.document);assert.equal(c.selectionError,null);d.window.close();
});
