const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
function setup(){const dom=new JSDOM('<main></main>',{url:'https://extension.test',runScripts:'outside-only'}),w=dom.window;w.eval(fs.readFileSync('src/shared/model.js','utf8'));w.eval(fs.readFileSync('src/shared/conversation.js','utf8'));let state={items:[]},context=w.GHE.parseContext('https://github.com/o/r/issues/1');let data={conversation:{loadedOnly:true,truncated:false,comments:[{id:'issuecomment-1',url:context.url+'#issuecomment-1',author:'alice',body:'Race condition <img src=x onerror=alert(1)>',kind:'comment'},{id:'issuecomment-2',url:context.url+'#issuecomment-2',author:'bob',body:'Tests cover empty input',kind:'comment'}]}};const calls=[],notices=[];let fail=false,ui;ui=w.GHE.mountConversation(w.document.querySelector('main'),{getState:()=>state,getContext:()=>context,getPageData:()=>data,request:async m=>{calls.push(m);if(fail)throw Error('Storage full');if(m.type==='SAVE_ITEM')state.items.push(m.context);return state;},onState:s=>{state=s;ui.render();},notify:(...x)=>notices.push(x),pageAction:async m=>calls.push(m)});ui.render();return{dom,w,ui,calls,notices,setFail:()=>fail=true,setData:x=>data=x,setContext:x=>context=x};}
const tick=()=>new Promise(r=>setTimeout(r,0));function input(x,label,value,event='input'){const el=x.w.document.querySelector(`[aria-label="${label}"]`);el.value=value;el.dispatchEvent(new x.w.Event(event));}
test('conversation searches loaded text and author, combines filters, and does not interpret HTML',()=>{const x=setup(),d=x.w.document;assert.match(d.body.textContent,/2 loaded/);assert.equal(d.querySelector('img'),null);input(x,'Search loaded comments','race');assert.equal(d.querySelectorAll('.conversation-card').length,1);input(x,'Filter comment author','bob','change');assert.equal(d.querySelectorAll('.conversation-card').length,0);input(x,'Search loaded comments','');assert.equal(d.querySelectorAll('.conversation-card').length,1);assert.match(d.body.textContent,/Tests cover/);x.dom.window.close();});
test('important comment saves a verified permalink and jump only sends the native id',async()=>{const x=setup(),d=x.w.document;d.querySelector('[data-conversation="save"]').click();await tick();assert.equal(x.calls[0].type,'SAVE_ITEM');assert.equal(x.calls[0].context.url,'https://github.com/o/r/issues/1#issuecomment-1');assert.match(x.calls[0].context.title,/alice/);d.querySelector('[aria-label="Only saved comments"]').click();assert.equal(d.querySelectorAll('.conversation-card').length,1);d.querySelector('[data-conversation="jump"]').click();await tick();assert.equal(x.calls[1].id,'issuecomment-1');assert.equal(x.calls[1].type,'conversation-jump');x.dom.window.close();});
test('failure never shows a comment as saved and refresh retains query focus',async()=>{const x=setup(),d=x.w.document;x.setFail();d.querySelector('[data-conversation="save"]').click();await tick();assert.equal(d.querySelector('[data-conversation="save"]').disabled,false);assert.match(x.notices.at(-1)[0],/Storage full/);const q=d.querySelector('[aria-label="Search loaded comments"]');q.focus();input(x,'Search loaded comments','alice');x.ui.render();assert.equal(d.activeElement.getAttribute('aria-label'),'Search loaded comments');assert.equal(d.activeElement.value,'alice');x.dom.window.close();});
test('empty, capped and unsupported snapshots never imply a complete thread',()=>{const x=setup(),d=x.w.document;x.setData({conversation:{comments:[],loadedOnly:true,truncated:true}});x.ui.render();assert.match(d.body.textContent,/limit/i);assert.match(d.body.textContent,/No readable comments/);x.setData({});x.ui.render();assert.equal(d.querySelector('main').textContent,'');x.dom.window.close();});
test('late search matches appear in a safe contextual excerpt',()=>{const x=setup(),d=x.w.document;const text='Opening context '.repeat(25)+'<img src=x> DECISION: keep the cache. Closing context';x.setData({conversation:{loadedOnly:true,truncated:false,comments:[{id:'issuecomment-3',url:'https://github.com/o/r/issues/1#issuecomment-3',author:'alice',body:text,kind:'comment'}]}});x.ui.render();input(x,'Search loaded comments','decision');const summary=d.querySelector('summary');assert.match(summary.textContent,/DECISION: keep the cache/);assert.equal(summary.querySelector('mark').textContent,'DECISION');assert.equal(d.querySelector('img'),null);assert.match(summary.textContent,/^…/);x.dom.window.close();});
test('saving preserves expansion and moves focus to a usable action even after parent detaches root',async()=>{const x=setup(),d=x.w.document;const details=d.querySelector('details');details.open=true;const save=d.querySelector('[data-conversation=save]');save.focus();save.click();const root=d.querySelector('main');root.remove();d.body.append(root);x.ui.render();await tick();assert.equal(d.querySelector('details').open,true);assert.equal(d.activeElement.dataset.conversation,'jump');assert.equal(d.activeElement.dataset.id,'issuecomment-1');assert.equal(d.activeElement.disabled,false);x.dom.window.close();});
test('failed save keeps expansion and returns focus to retry while query changes keep open state',async()=>{const x=setup(),d=x.w.document;x.setFail();d.querySelector('details').open=true;const save=d.querySelector('[data-conversation=save]');save.focus();save.click();await tick();assert.equal(d.querySelector('details').open,true);assert.equal(d.activeElement.dataset.conversation,'save');input(x,'Search loaded comments','race');assert.equal(d.querySelector('details').open,true);x.setContext(x.w.GHE.parseContext('https://github.com/o/r/issues/2'));x.ui.render();assert.equal(d.querySelector('details').open,false);x.dom.window.close();});
test('search refresh preserves the complete selected text range',()=>{const x=setup(),d=x.w.document;input(x,'Search loaded comments','alice');const search=d.querySelector('[aria-label="Search loaded comments"]');search.focus();search.setSelectionRange(1,4);x.ui.render();assert.equal(d.activeElement.selectionStart,1);assert.equal(d.activeElement.selectionEnd,4);x.dom.window.close();});
test('storage refresh after a successful save preserves comment action focus',async()=>{const x=setup(),d=x.w.document;const save=d.querySelector('[data-conversation=save]');save.focus();save.click();await tick();assert.equal(d.activeElement.dataset.conversation,'jump');x.ui.render();assert.equal(d.activeElement.dataset.conversation,'jump');assert.equal(d.activeElement.dataset.id,'issuecomment-1');assert.equal(d.activeElement.disabled,false);x.dom.window.close();});
test('refresh does not take focus from outside the conversation',async()=>{const x=setup(),d=x.w.document;const outside=d.createElement('button');d.body.append(outside);outside.focus();x.ui.render();assert.equal(d.activeElement,outside);d.querySelector('[data-conversation=jump]').click();await tick();assert.equal(d.activeElement,outside);x.dom.window.close();});
test('results refresh retains the focused action for its comment',()=>{const x=setup(),d=x.w.document;const jump=d.querySelector('[data-conversation=jump]');jump.focus();input(x,'Search loaded comments','race');assert.equal(d.activeElement.dataset.conversation,'jump');assert.equal(d.activeElement.dataset.id,'issuecomment-1');x.dom.window.close();});
test('jump completion does not refocus the panel after source navigation',async()=>{const x=setup(),d=x.w.document;const jump=d.querySelector('[data-conversation=jump]');jump.focus();jump.click();const outside=d.createElement('button');d.body.append(outside);outside.focus();await tick();x.ui.render();assert.equal(d.activeElement,outside);x.dom.window.close();});
