const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
function setup(options={}){const dom=new JSDOM('<main></main>',{url:'https://extension.test',runScripts:'outside-only'});const w=dom.window;let state={items:[{url:'https://github.com/o/r/issues/1',title:'Investigate race',repo:'o/r',note:'Existing note'}],snippets:[{id:'snippet1',title:'Race source',path:'src/app.js',code:'return 1',url:'https://github.com/o/r/blob/main/src/app.js#L1',language:'javascript',lineStart:1,lineEnd:1}],workspaces:[]};const messages=[];let copied='';w.eval(fs.readFileSync('src/shared/model.js','utf8'));Object.assign(w.GHE,{markdownLink:c=>`[${c.title}](${c.url})`,snippetMarkdown:s=>s.code});w.eval(fs.readFileSync('src/shared/workspaces.js','utf8'));if(options.state)state=structuredClone(options.state);const request=async m=>{messages.push(m);await options.beforeRequest?.(m);if(m.type==='CREATE_WORKSPACE')state.workspaces.push({id:'w1',title:m.title,note:'',itemUrls:[],snippetIds:[]});if(m.type==='LINK_WORKSPACE_ITEM')state.workspaces[0].itemUrls.push(m.url);if(m.type==='LINK_WORKSPACE_SNIPPET')state.workspaces[0].snippetIds.push(m.snippetId);if(m.type==='UPDATE_WORKSPACE')Object.assign(state.workspaces[0],m.patch);return structuredClone(state);};let ui;ui=w.GHE.mountWorkspaces(w.document.querySelector('main'),{...options,getState:()=>state,getContext:()=>state.items[0],request,onState:s=>{state=s;ui.render();},notify:()=>{},copy:async s=>copied=s,openPages:async()=>{}});ui.render();return{dom,w,ui,messages,getState:()=>state,getCopied:()=>copied};}
const tick=()=>new Promise(r=>setTimeout(r,0));
test('workspace combines saved pages and snippets and exports their sources',async()=>{const x=setup(),d=x.w.document;d.querySelector('[aria-label="New workspace name"]').value='Race investigation';d.querySelector('[data-ws="create"]').click();await tick();assert.equal(x.getState().workspaces.length,1);d.querySelector('[data-ws="add-current"]').click();await tick();assert.deepEqual(x.getState().workspaces[0].itemUrls,['https://github.com/o/r/issues/1']);d.querySelector('[aria-label="Add a saved snippet"]').value='snippet1';d.querySelector('[data-ws="add-snippet"]').click();await tick();assert.deepEqual(x.getState().workspaces[0].snippetIds,['snippet1']);assert.equal([...d.querySelectorAll('a')].find(a=>a.textContent==='Race source').hash,'#L1');d.querySelector('[data-ws="copy"]').click();await tick();assert.match(x.getCopied(),/Race investigation/);assert.match(x.getCopied(),/Investigate race/);assert.match(x.getCopied(),/return 1/);x.dom.window.close();});
test('unsaved workspace note survives unrelated state refreshes',async()=>{const x=setup(),d=x.w.document;d.querySelector('[aria-label="New workspace name"]').value='Notes';d.querySelector('[data-ws="create"]').click();await tick();const n=d.querySelector('[aria-label="Workspace note"]');n.value='Keep this draft';n.dispatchEvent(new x.w.Event('input'));x.ui.render();assert.equal(d.querySelector('[aria-label="Workspace note"]').value,'Keep this draft');d.querySelector('[data-ws="save-note"]').click();await tick();assert.equal(x.getState().workspaces[0].note,'Keep this draft');x.dom.window.close();});
test('workspace creation and rename text survive unrelated refreshes',async()=>{const x=setup(),d=x.w.document;const name=d.querySelector('[aria-label="New workspace name"]');name.value='Investigation in progress';name.dispatchEvent(new x.w.Event('input'));x.ui.render();assert.equal(d.querySelector('[aria-label="New workspace name"]').value,'Investigation in progress');d.querySelector('[data-ws="create"]').click();await tick();assert.equal(d.querySelector('[aria-label="New workspace name"]').value,'');d.querySelector('[data-ws="rename"]').click();const rename=d.querySelector('[aria-label="Rename workspace"]');rename.value='Renamed investigation';rename.dispatchEvent(new x.w.Event('input'));x.ui.render();assert.equal(d.querySelector('[aria-label="Rename workspace"]').value,'Renamed investigation');d.querySelector('[data-ws="save-name"]').click();await tick();assert.equal(x.getState().workspaces[0].title,'Renamed investigation');assert.equal(d.querySelector('[aria-label="Rename workspace"]'),null);x.dom.window.close();});

function recovery(store,overrides={}){return {loadToolDrafts:async kind=>Object.entries(store).map(([key,value])=>[key,structuredClone(value)]),saveToolDraft:async(kind,key,value)=>{store[key]=structuredClone(value);},deleteToolDraft:async(kind,key,expected)=>{if(JSON.stringify(store[key])===JSON.stringify(expected))delete store[key];},...overrides};}
function type(x,label,value){const input=x.w.document.querySelector(`[aria-label="${label}"]`);input.value=value;input.dispatchEvent(new x.w.Event('input'));}
function choose(x,id='w1'){const select=x.w.document.querySelector('[aria-label="Choose workspace"]');select.value=id;select.dispatchEvent(new x.w.Event('change'));}
const workspaceState=()=>({items:[],snippets:[],workspaces:[{id:'w1',title:'Investigation',note:'Committed',itemUrls:[],snippetIds:[]}]});
test('workspace note, creation and rename drafts recover on remount and clear only when committed',async()=>{
 const store={},state=workspaceState(),x=setup({...recovery(store),state});await x.ui.ready;choose(x);type(x,'Workspace note','Remember edge case');type(x,'New workspace name','Next investigation');x.w.document.querySelector('[data-ws="rename"]').click();type(x,'Rename workspace','Better title');await tick();x.dom.window.close();
 const y=setup({...recovery(store),state});assert.ok(y.ui.ready instanceof y.w.Promise);await y.ui.ready;choose(y);assert.equal(y.w.document.querySelector('[aria-label="Workspace note"]').value,'Remember edge case');assert.equal(y.w.document.querySelector('[aria-label="New workspace name"]').value,'Next investigation');assert.equal(y.w.document.querySelector('[aria-label="Rename workspace"]').value,'Better title');assert.equal(y.ui.hasDrafts(),true);
 y.w.document.querySelector('[data-ws="save-note"]').click();await tick();assert.equal(y.getState().workspaces[0].note,'Remember edge case');assert.equal(store['note:w1'],undefined);assert.deepEqual(store['rename:w1'],{title:'Better title'});y.dom.window.close();
});
test('late recovery cannot replace a touched or discarded draft',async()=>{
 let resolve;const pending=new Promise(r=>resolve=r);const x=setup({...recovery({}, {loadToolDrafts:()=>pending}),state:workspaceState()});choose(x);type(x,'Workspace note','New input');type(x,'New workspace name','Fresh title');resolve([['note:w1',{note:'Old recovered'}],['create',{title:'Old title'}]]);await x.ui.ready;assert.equal(x.w.document.querySelector('[aria-label="Workspace note"]').value,'New input');assert.equal(x.w.document.querySelector('[aria-label="New workspace name"]').value,'Fresh title');x.w.document.querySelector('[data-ws="discard-note"]').click();await tick();assert.equal(x.w.document.querySelector('[aria-label="Workspace note"]').value,'Committed');x.dom.window.close();
});
test('saving an older note does not erase a newer draft on this surface or another',async()=>{
 const store={};let release;const gate=new Promise(r=>release=r);const x=setup({...recovery(store),state:workspaceState(),beforeRequest:m=>m.type==='UPDATE_WORKSPACE'?gate:undefined});await x.ui.ready;choose(x);type(x,'Workspace note','Submitted');x.w.document.querySelector('[data-ws="save-note"]').click();type(x,'Workspace note','Newer local');await tick();store['note:w1']={note:'Newer other surface'};release();await tick();assert.equal(x.w.document.querySelector('[aria-label="Workspace note"]').value,'Newer local');assert.deepEqual(store['note:w1'],{note:'Newer other surface'});assert.equal(x.getState().workspaces[0].note,'Submitted');x.dom.window.close();
});

test('successful create and rename clear the exact recovered snapshots',async()=>{
 const store={create:{title:'Recovered title'}},x=setup(recovery(store));await x.ui.ready;x.w.document.querySelector('[data-ws="create"]').click();await tick();assert.equal(store.create,undefined);assert.equal(x.w.document.querySelector('[aria-label="New workspace name"]').value,'');x.w.document.querySelector('[data-ws="rename"]').click();type(x,'Rename workspace','Renamed');await tick();x.w.document.querySelector('[data-ws="save-name"]').click();await tick();assert.equal(store['rename:w1'],undefined);assert.equal(x.getState().workspaces[0].title,'Renamed');assert.equal(x.ui.hasDrafts(),false);x.dom.window.close();
});
test('discard before recovery settles prevents an old note from returning',async()=>{
 let release;const pending=new Promise(r=>release=r),store={};const x=setup({...recovery(store,{loadToolDrafts:()=>pending}),state:workspaceState()});choose(x);type(x,'Workspace note','Temporary');x.w.document.querySelector('[data-ws="discard-note"]').click();await tick();release([['note:w1',{note:'Old session copy'}]]);await x.ui.ready;assert.equal(x.w.document.querySelector('[aria-label="Workspace note"]').value,'Committed');assert.equal(x.ui.hasDrafts(),false);assert.equal(store['note:w1'],undefined);x.dom.window.close();
});
test('failed note commit retains recovery and user edits',async()=>{
 const store={},x=setup({...recovery(store),state:workspaceState(),beforeRequest:()=>{throw new Error('Storage full');}});await x.ui.ready;choose(x);type(x,'Workspace note','Must retain');await tick();x.w.document.querySelector('[data-ws="save-note"]').click();await tick();assert.equal(x.getState().workspaces[0].note,'Committed');assert.deepEqual(store['note:w1'],{note:'Must retain'});assert.equal(x.w.document.querySelector('[aria-label="Workspace note"]').value,'Must retain');x.dom.window.close();
});

test('creation focus and selected text survive refresh with no workspace selected',async()=>{
 const x=setup();await x.ui.ready;const input=x.w.document.querySelector('[aria-label="New workspace name"]');type(x,'New workspace name','Investigation title');input.focus();input.setSelectionRange(2,9);x.ui.render();const current=x.w.document.querySelector('[aria-label="New workspace name"]');assert.equal(x.w.document.activeElement,current);assert.equal(current.selectionStart,2);assert.equal(current.selectionEnd,9);x.dom.window.close();
});

test('controller selection opens an existing workspace and ignores missing IDs',async()=>{const x=setup({state:workspaceState()});await x.ui.ready;assert.equal(x.ui.select('w1'),true);assert.equal(x.w.document.querySelector('[aria-label="Workspace note"]').value,'Committed');assert.equal(x.ui.select('missing'),false);assert.equal(x.w.document.querySelector('[aria-label="Choose workspace"]').value,'w1');x.dom.window.close();});

test('workspace exports disclose unsaved edits and include only saved notes',async()=>{
 const x=setup({state:workspaceState()});await x.ui.ready;x.ui.select('w1');type(x,'Workspace note','Unsaved private thought');assert.match(x.w.document.querySelector('[data-workspace-export-notice]').textContent,/Export uses saved notes/);assert.equal(x.w.document.querySelector('[data-workspace-export-notice]').hidden,false);x.w.document.querySelector('[data-ws="copy"]').click();await tick();assert.match(x.getCopied(),/Committed/);assert.doesNotMatch(x.getCopied(),/Unsaved private thought/);assert.equal(x.messages.length,0);x.dom.window.close();
});
test('linked PR file notes are an explicit counted export option and exclude unlinked review records',async()=>{
 const state=workspaceState(),urls=['https://github.com/o/r/pull/4','https://github.com/o/r/pull/4/changes#diff-x'];state.workspaces[0].itemUrls=urls;state.items=urls.map(url=>({url,title:'Linked PR',repo:'o/r',note:''}));state.reviews=[{prUrl:urls[0],files:[{path:'src/[a].js',note:'Saved finding <script>'},{path:'empty.js',note:' '}]},{prUrl:'https://github.com/o/r/pull/9',files:[{path:'secret.js',note:'UNLINKED SECRET'}]}];
 const x=setup({state});await x.ui.ready;x.ui.select('w1');const checkbox=x.w.document.querySelector('[data-workspace-review-export]');assert.ok(checkbox);assert.equal(checkbox.checked,false);assert.match(checkbox.parentElement.textContent,/Include 1 saved private PR file note/);x.w.document.querySelector('[data-ws="copy"]').click();await tick();assert.doesNotMatch(x.getCopied(),/Saved finding/);checkbox.checked=true;checkbox.dispatchEvent(new x.w.Event('change'));x.w.document.querySelector('[data-ws="copy"]').click();await tick();const output=x.getCopied();assert.equal((output.match(/Saved finding/g)||[]).length,1);assert.match(output,/https:\/\/github.com\/o\/r\/pull\/4/);assert.ok(output.includes('src/\\[a\\]\\.js'));assert.match(output,/&lt;script&gt;/);assert.doesNotMatch(output,/UNLINKED SECRET|verified|complete/i);x.dom.window.close();
});

test('workspace export retains linked destinations removed from Saved without resurrecting their notes',async()=>{
 const state=workspaceState();state.workspaces[0].itemUrls=['https://github.com/o/r/issues/8#issuecomment-12'];const x=setup({state});await x.ui.ready;x.ui.select('w1');x.w.document.querySelector('[data-ws="copy"]').click();await tick();assert.match(x.getCopied(),/https:\/\/github.com\/o\/r\/issues\/8#issuecomment-12/);assert.match(x.getCopied(),/Saved page removed/);assert.equal(x.getState().items.length,0);x.dom.window.close();
});

test('workspace chooser keeps focus after changing selection',async()=>{
 const x=setup({state:workspaceState()});await x.ui.ready;const picker=x.w.document.querySelector('[aria-label="Choose workspace"]');picker.focus();picker.value='w1';picker.dispatchEvent(new x.w.Event('change'));assert.equal(x.w.document.activeElement,x.w.document.querySelector('[aria-label="Choose workspace"]'));x.dom.window.close();
});

test('workspace Markdown discloses unavailable excerpt references instead of implying complete evidence',()=>{
 const x=setup(),markdown=x.w.GHE.workspaceMarkdown({title:'Evidence',note:'',itemUrls:[],snippetIds:['removed-id']},{items:[],snippets:[],reviews:[]});assert.match(markdown,/1 linked code excerpt is unavailable/);assert.doesNotMatch(markdown,/undefined/);x.dom.window.close();
});
